on:
  push:
    branches:
      main
jobs:
  build-apk:
    name: Build APK for Android
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
